import { boolean, integer, jsonb, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID
  name: text('name'),
  email: text('email').notNull(),
  phone: text('phone'),
  role: text('role').default('customer').notNull(),
  address: text('address'),
  area: text('area'),
  city: text('city'),
  pincode: text('pincode'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const orders = pgTable('orders', {
  id: text('id').primaryKey(),
  orderNumber: text('order_number').notNull(),
  customerId: text('customer_id'),
  customerName: text('customer_name').notNull(),
  customerPhone: text('customer_phone').notNull(),
  customerEmail: text('customer_email'),
  items: jsonb('items'),
  subtotal: integer('subtotal').notNull(),
  couponCode: text('coupon_code'),
  couponDiscount: integer('coupon_discount').default(0),
  subscriptionDiscount: integer('subscription_discount').default(0),
  deliveryFee: integer('delivery_fee').default(0),
  totalAmount: integer('total_amount').notNull(),
  paymentMethod: text('payment_method').default('razorpay'),
  paymentStatus: text('payment_status').default('pending'),
  razorpayOrderId: text('razorpay_order_id'),
  razorpayPaymentId: text('razorpay_payment_id'),
  orderStatus: text('order_status').default('pending'),
  deliveryAddress: jsonb('delivery_address'),
  deliveryDate: text('delivery_date'),
  deliverySlot: text('delivery_slot'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const subscriptions = pgTable('subscriptions', {
  id: text('id').primaryKey(),
  subscriptionNumber: text('subscription_number').notNull(),
  customerId: text('customer_id'),
  customerName: text('customer_name').notNull(),
  customerPhone: text('customer_phone').notNull(),
  customerEmail: text('customer_email'),
  planId: text('plan_id').notNull(),
  planName: text('plan_name').notNull(),
  mealType: text('meal_type').default('veg'),
  mealsTotal: integer('meals_total').notNull(),
  mealsUsed: integer('meals_used').default(0),
  mealsRemaining: integer('meals_remaining').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  deliveryFrequency: text('delivery_frequency').default('daily_lunch'),
  deliverySlot: text('delivery_slot'),
  deliveryAddress: jsonb('delivery_address'),
  basePrice: integer('base_price').notNull(),
  cashbackAmount: integer('cashback_amount').default(0),
  finalPaid: integer('final_paid').notNull(),
  paymentStatus: text('payment_status').default('paid'),
  status: text('status').default('active'),
  orderId: text('order_id'),
  isLongTerm: boolean('is_long_term').default(false),
  totalAllowedPauseDays: integer('total_allowed_pause_days').default(15),
  totalPauseDaysUsed: integer('total_pause_days_used').default(0),
  remainingPauseDays: integer('remaining_pause_days').default(15),
  cancellationDetails: jsonb('cancellation_details'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const cancellationPolicy = pgTable('cancellation_policy', {
  id: text('id').primaryKey(),
  standardMealRate: numeric('standard_meal_rate').default('123.08').notNull(),
  adminFee: numeric('admin_fee').default('500.00').notNull(),
  policyNotes: text('policy_notes'),
  updatedAt: timestamp('updated_at').defaultNow(),
});
